version: "3.7"
services:

  dbt-env:
    image: circleci/python:3.6.2-stretch
    environment:
        CI_DBT_HOST: postgres
        CI_DBT_USER: root
        CI_DBT_PASS: ''
        CI_DBT_PORT: 5432
        CI_DBT_DBNAME: circle_test
        CI_SPARK_THRIFT_DBT_HOST: spark
        CI_SPARK_THRIFT_DBT_PORT: 10000
        CI_SPARK_THRIFT_DBT_USER: dbt
    volumes:
        - ".:/repo"

  postgres:
    image: circleci/postgres:9.6.5-alpine-ram
    ports:
      - "5432:5432"
  
  spark:
    image: godatadriven/spark:2
    ports:
        - "10000:10000"
        - "4040:4040"
    command: >
        --class org.apache.spark.sql.hive.thriftserver.HiveThriftServer2
        --name Thrift JDBC/ODBC Server
        